// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// $Rev: 18756 $
// File generated on 2018-06-12 오후 5:45:42 from Type Library described below.

// ************************************************************************  //
// Type Lib: C:\Program Files (x86)\Common Files\WacomGSS\FlSigCOM.dll (1)
// LIBID: {B0452E4E-DB2A-472D-91EA-9F77C9885A39}
// LCID: 0
// Helpfile: 
// HelpString: FlSigCtl 1.0 Type Library
// DepndLst: 
//   (1) v2.0 stdole, (C:\Windows\SysWOW64\stdole2.tlb)
// ************************************************************************ //
#ifndef   FLSIGCTLLib_OCXH
#define   FLSIGCTLLib_OCXH

#pragma option push -b -a4 -w-inl

#include <olectrls.hpp>
#include <oleserver.hpp>
#if !defined(__UTILCLS_H)
#include <utilcls.h>
#endif
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0700)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <stdvcl.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "FLSIGCTLLib_TLB.h"
namespace Flsigctllib_tlb
{

// *********************************************************************//
// HelpString: FlSigCtl 1.0 Type Library
// Version:    1.0
// *********************************************************************//


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TSigObj
// Help String      : SigObj Class
// Default Interface: ISigObj3
// Def. Intf. Object: ISigObj3Ptr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TSigObj : public Oleserver::TOleServer
{
  ISigObj3Ptr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TSigObj(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  ISigObj3Ptr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(ISigObj3Ptr intf);


  VARIANT         __fastcall get_SigData(void);
  void            __fastcall set_SigData(VARIANT pVal/*[in]*/);
  void            __fastcall set_SigText(BSTR pstrText/*[in]*/);
  BSTR            __fastcall get_SigText(void);
  VARIANT_BOOL    __fastcall get_IsCaptured(void);
  long            __fastcall get_Width(void);
  long            __fastcall get_Height(void);
  BSTR            __fastcall get_Who(void);
  BSTR            __fastcall get_Why(void);
  DATE            __fastcall get_When(Flsigctllib_tlb::TimeZone TZ/*[in,def,opt]*/);
  VARIANT         __fastcall get_AdditionalData(Flsigctllib_tlb::CaptData DataType/*[in]*/);
  BSTR            __fastcall get_Ink(void);
  void            __fastcall set_Ink(BSTR pVal/*[in]*/);
  VARIANT_BOOL    __fastcall get_CrossedOut(void);
  BSTR            __fastcall get_ExtraData(BSTR Key/*[in]*/);
  void            __fastcall set_ExtraData(BSTR Key/*[in]*/, BSTR pVal/*[in]*/);
  void            __fastcall Clear(void);
  Flsigctllib_tlb::IntegrityStatus __fastcall CheckIntegrity(VARIANT Key/*[in,opt]*/= TNoParam());
  Flsigctllib_tlb::SignedData __fastcall CheckSignedData(Flsigctllib_tlb::IHash* Hash/*[in]*/);
  void            __fastcall Render(long hDCTarg/*[in]*/, long hDCRef/*[in]*/, long x/*[in]*/, 
                                    long y/*[in]*/, float InkWidth/*[in,def,opt]*/, 
                                    ::OLE_COLOR InkColor/*[in,def,opt]*/, 
                                    VARIANT_BOOL Line/*[in,def,opt]*/, short Zoom/*[in,def,opt]*/, 
                                    short Rotation/*[in,def,opt]*/);
  void            __fastcall RenderRect(long hDCTarg/*[in]*/, long hDCRef/*[in]*/, long Left/*[in]*/, 
                                        long Top/*[in]*/, long Right/*[in]*/, long Bottom/*[in]*/, 
                                        float InkWidth/*[in,def,opt]*/, 
                                        ::OLE_COLOR InkColor/*[in,def,opt]*/, 
                                        Flsigctllib_tlb::DisplayMode Option/*[in,def,opt]*/, 
                                        short Zoom/*[in,def,opt]*/, short Rotation/*[in,def,opt]*/);
  VARIANT_BOOL    __fastcall SetProperty(BSTR Name/*[in]*/, VARIANT Value/*[in]*/);
  VARIANT         __fastcall GetProperty(BSTR Name/*[in]*/);
  VARIANT         __fastcall RenderBitmap(BSTR OutputFilename/*[in]*/, long DimensionX/*[in]*/, 
                                          long DimensionY/*[in]*/, BSTR MimeType/*[in]*/, 
                                          float InkWidth/*[in]*/, ::OLE_COLOR InkColor/*[in]*/, 
                                          ::OLE_COLOR BackgroundColor/*[in]*/, 
                                          float PaddingX/*[in]*/, float PaddingY/*[in]*/, 
                                          Flsigctllib_tlb::RBFlags Flags/*[in]*/);
  IPictureDisp*   __fastcall Picture(long DimensionX/*[in]*/, long DimensionY/*[in]*/, 
                                     BSTR MimeType/*[in]*/, float InkWidth/*[in]*/, 
                                     ::OLE_COLOR InkColor/*[in]*/, 
                                     ::OLE_COLOR BackgroundColor/*[in]*/, float PaddingX/*[in]*/, 
                                     float PaddingY/*[in]*/, Flsigctllib_tlb::RBFlags Flags/*[in]*/);
  Flsigctllib_tlb::ReadEncodedBitmapResult __fastcall ReadEncodedBitmap(VARIANT Bitmap/*[in]*/);
  __property VARIANT SigData={ read=get_SigData, write=set_SigData };
  __property VARIANT_BOOL IsCaptured={ read=get_IsCaptured };
  __property long Width={ read=get_Width };
  __property long Height={ read=get_Height };
  __property BSTR Who={ read=get_Who };
  __property BSTR Why={ read=get_Why };
  __property DATE When[Flsigctllib_tlb::TimeZone TZ]={ read=get_When };
  __property VARIANT AdditionalData[Flsigctllib_tlb::CaptData DataType]={ read=get_AdditionalData };
  __property VARIANT_BOOL CrossedOut={ read=get_CrossedOut };
  __property BSTR ExtraData[BSTR Key]={ read=get_ExtraData, write=set_ExtraData };
  __property BSTR SigText={ read=get_SigText, write=set_SigText, stored=false };
  __property BSTR Ink={ read=get_Ink, write=set_Ink, stored=false };
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TSigCtl
// Help String      : SigCtl Class
// Default Interface: ISigCtl3
// Def. Intf. Object: ISigCtl3Disp
// Def. Intf. DISP? : No
// Event   Interface: _ISigCtlEvents2
// TypeFlags        : (2) CanCreate
// *********************************************************************//

// *********************************************************************//
// Definition of closures to allow VCL handlers to catch OCX events.      
// *********************************************************************//
typedef void __fastcall (__closure * TSigCtlPreCapture)(System::TObject * Sender, 
                                                        BSTR Who/*[in]*/, BSTR Why/*[in]*/, 
                                                        VARIANT_BOOL* Continue/*[in,out]*/);
typedef void __fastcall (__closure * TSigCtlPostCapture)(System::TObject * Sender, 
                                                         long CaptureStatus/*[in]*/);
//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
// Proxy class to host SigCtl Class in CBuilder IDE/Applications.
//-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
class PACKAGE TSigCtl : public TOleControl
{
  OVERLOADED_PROP_METHODS;
  static TNoParam  OptParam;
  static GUID      DEF_CTL_INTF;

  // Instance of Closures to expose OCX Events as VCL ones
  //
  TSigCtlPreCapture              FOnPreCapture;
  TSigCtlPostCapture             FOnPostCapture;
  TNotifyEvent                   FOnRemove;

  // Default Interace of OCX
  //
  ISigCtl3Disp m_OCXIntf;

  // VCL Property Getters/Setters which delegate to OCX
  //
  LPDISPATCH      __fastcall get_Signature(void);
  void            __fastcall set_Signature(LPDISPATCH ppVal/*[in]*/);
  VARIANT         __fastcall get_AppData(VARIANT Key/*[in,opt]*/= TNoParam());
  void            __fastcall set_AppData(VARIANT Key/*[in,opt]*/, VARIANT pVal/*[in]*/);
  VARIANT         __fastcall get_Licence(void);
  void            __fastcall set_Licence(VARIANT pVal/*[in]*/);

  // Static variables used by all instances of OCX proxy
  //
  static int          EventDispIDs[3];
  static int          TFontIDs[1];
  static TControlData2 CControlData;
  static GUID          CTL_DEF_INTF;

  // Method providing access to interface as __property 
  //
  ISigCtl3Disp __fastcall GetDefaultInterface();
  ISigCtl3Disp __fastcall GetControlInterface()
  { return GetDefaultInterface(); }

protected:
  void     __fastcall CreateControl  ();
  void     __fastcall InitControlData();

public:
  virtual  __fastcall TSigCtl(TComponent* AOwner) : TOleControl(AOwner)
  {};
  virtual  __fastcall TSigCtl(HWND        Parent) : TOleControl(Parent)
  {};

  // OCX methods
  //
  Flsigctllib_tlb::CaptureResult __fastcall Capture(BSTR Who/*[in]*/, BSTR Why/*[in]*/, 
                                                    VARIANT What/*[in,opt]*/= TNoParam(), 
                                                    VARIANT Key/*[in,opt]*/= TNoParam());
  void            __fastcall AboutBox(void);
  VARIANT_BOOL    __fastcall SetProperty(BSTR Name/*[in]*/, VARIANT Value/*[in]*/);
  VARIANT         __fastcall GetProperty(BSTR Name/*[in]*/);

  // OCX properties
  //
  __property _di_IDispatch Signature={ read=GetIDispatchProp, write=SetIDispatchProp, index=1 };
  __property VARIANT AppData[VARIANT Key]={ read=get_AppData, write=set_AppData };
  __property System::OleVariant Licence={ read=GetOleVariantProp, write=SetOleVariantProp, index=17 };
  __property System::WideString Properties={ write=SetWideStringProp, index=18 };
  __property ISigCtl3Disp ControlInterface={ read=GetDefaultInterface };

  // Published properties
  //
__published:

  // Standard/Extended properties
  //
  __property ParentColor;
  __property ParentFont;
  __property Align;
  __property DragCursor;
  __property DragMode;
  __property ParentShowHint;
  __property PopupMenu;
  __property ShowHint;
  __property TabOrder;
  __property Visible;
  __property OnDragDrop;
  __property OnDragOver;
  __property OnEndDrag;
  __property OnEnter;
  __property OnExit;
  __property OnStartDrag;
  __property OnMouseUp;
  __property OnMouseMove;
  __property OnMouseDown;
  __property OnKeyUp;
  __property OnKeyPress;
  __property OnKeyDown;
  __property OnDblClick;
  __property OnClick;

  // OCX properties
  //
  __property Graphics::TColor BackColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=-501 };
  __property int BackStyle={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=-502 };
  __property Graphics::TColor BorderColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=-503 };
  __property int BorderStyle={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=-504 };
  __property int BorderWidth={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=-505 };
  __property Graphics::TFont * Font={ read=GetTFontProp, write=_SetTFontProp, stored=false, index=-512 };
  __property Graphics::TColor ForeColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=-513 };
  __property bool Enabled={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=-514 };
  __property bool TabStop={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=-516 };
  __property System::WideString Caption={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=-518 };
  __property bool BorderVisible={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=-519 };
  __property short CtlPadding={ read=GetSmallintProp, write=SetSmallintProp, stored=false, index=2 };
  __property Activex::TOleEnum DisplayMode={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=3 };
  __property short Zoom={ read=GetSmallintProp, write=SetSmallintProp, stored=false, index=4 };
  __property short Rotation={ read=GetSmallintProp, write=SetSmallintProp, stored=false, index=5 };
  __property Graphics::TColor InkColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=6 };
  __property float InkWidth={ read=GetSingleProp, write=SetSingleProp, stored=false, index=7 };
  __property Activex::TOleEnum ShowWho={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=8 };
  __property Activex::TOleEnum ShowWhen={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=9 };
  __property Activex::TOleEnum ShowWhy={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=12 };
  __property System::WideString WhenFormat={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=10 };
  __property System::WideString InputWho={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=13 };
  __property System::WideString InputWhy={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=14 };
  __property System::WideString InputData={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=15 };
  __property System::WideString InputSignature={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=16 };

  // OCX Events
  //
  __property TSigCtlPreCapture OnPreCapture={ read=FOnPreCapture, write=FOnPreCapture };
  __property TSigCtlPostCapture OnPostCapture={ read=FOnPostCapture, write=FOnPostCapture };
  __property TNotifyEvent OnRemove={ read=FOnRemove, write=FOnRemove };
};
typedef TSigCtl  TSigCtlProxy;


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TSigCtlSigDisplayProp
// Help String      : SigCtlSigDisplayProp Class
// Default Interface: IUnknown
// Def. Intf. Object: IUnknownPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TSigCtlSigDisplayProp : public Oleserver::TOleServer
{
  IUnknownPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TSigCtlSigDisplayProp(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  IUnknownPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IUnknownPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TSigCtlTextDisplayProp
// Help String      : SigCtlTextDisplayProp Class
// Default Interface: IUnknown
// Def. Intf. Object: IUnknownPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TSigCtlTextDisplayProp : public Oleserver::TOleServer
{
  IUnknownPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TSigCtlTextDisplayProp(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  IUnknownPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IUnknownPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TSigCtlBorderProp
// Help String      : SigCtlBorderProp Class
// Default Interface: IUnknown
// Def. Intf. Object: IUnknownPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TSigCtlBorderProp : public Oleserver::TOleServer
{
  IUnknownPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TSigCtlBorderProp(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  IUnknownPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IUnknownPtr intf);


};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : THash
// Help String      : Hash Class
// Default Interface: IHash
// Def. Intf. Object: IHashPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE THash : public Oleserver::TOleServer
{
  IHashPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall THash(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  IHashPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IHashPtr intf);


  Flsigctllib_tlb::HashType __fastcall get_Type(void);
  void            __fastcall set_Type(Flsigctllib_tlb::HashType pVal/*[in]*/);
  BSTR            __fastcall get_Hash(void);
  void            __fastcall Add(VARIANT Data/*[in]*/);
  void            __fastcall Clear(void);
  __property BSTR Hash={ read=get_Hash };
  __property Flsigctllib_tlb::HashType Type={ read=get_Type, write=set_Type, stored=false };
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TKey
// Help String      : Key Class
// Default Interface: IKey
// Def. Intf. Object: IKeyPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TKey : public Oleserver::TOleServer
{
  IKeyPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TKey(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  IKeyPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IKeyPtr intf);


  Flsigctllib_tlb::KeyType __fastcall get_Type(void);
  void            __fastcall Set_(Flsigctllib_tlb::KeyType Type/*[in]*/, 
                                  VARIANT Value/*[in,opt]*/= TNoParam());
  __property Flsigctllib_tlb::KeyType Type={ read=get_Type };
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TSigCtlXHTML
// Help String      : SigCtlXHTML Class
// Default Interface: ISigCtlXHTML4
// Def. Intf. Object: ISigCtlXHTML4Disp
// Def. Intf. DISP? : No
// Event   Interface: _ISigCtlEvents2
// TypeFlags        : (2) CanCreate
// *********************************************************************//

// *********************************************************************//
// Definition of closures to allow VCL handlers to catch OCX events.      
// *********************************************************************//
typedef void __fastcall (__closure * TSigCtlXHTMLPreCapture)(System::TObject * Sender, 
                                                             BSTR Who/*[in]*/, BSTR Why/*[in]*/, 
                                                             VARIANT_BOOL* Continue/*[in,out]*/);
typedef void __fastcall (__closure * TSigCtlXHTMLPostCapture)(System::TObject * Sender, 
                                                              long CaptureStatus/*[in]*/);
//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
// Proxy class to host SigCtlXHTML Class in CBuilder IDE/Applications.
//-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
class PACKAGE TSigCtlXHTML : public TOleControl
{
  OVERLOADED_PROP_METHODS;
  static TNoParam  OptParam;
  static GUID      DEF_CTL_INTF;

  // Instance of Closures to expose OCX Events as VCL ones
  //
  TSigCtlXHTMLPreCapture         FOnPreCapture;
  TSigCtlXHTMLPostCapture        FOnPostCapture;
  TNotifyEvent                   FOnRemove;

  // Default Interace of OCX
  //
  ISigCtlXHTML4Disp m_OCXIntf;

  // VCL Property Getters/Setters which delegate to OCX
  //
  LPDISPATCH      __fastcall get_Signature(void);
  void            __fastcall set_Signature(LPDISPATCH ppVal/*[in]*/);
  VARIANT         __fastcall get_AppData(VARIANT Key/*[in,opt]*/= TNoParam());
  void            __fastcall set_AppData(VARIANT Key/*[in,opt]*/, VARIANT pVal/*[in]*/);
  LPDISPATCH      __fastcall get_Printer(void);
  VARIANT         __fastcall get_Licence(void);
  void            __fastcall set_Licence(VARIANT pVal/*[in]*/);

  // Static variables used by all instances of OCX proxy
  //
  static int          EventDispIDs[3];
  static int          TFontIDs[1];
  static TControlData2 CControlData;
  static GUID          CTL_DEF_INTF;

  // Method providing access to interface as __property 
  //
  ISigCtlXHTML4Disp __fastcall GetDefaultInterface();
  ISigCtlXHTML4Disp __fastcall GetControlInterface()
  { return GetDefaultInterface(); }

protected:
  void     __fastcall CreateControl  ();
  void     __fastcall InitControlData();

public:
  virtual  __fastcall TSigCtlXHTML(TComponent* AOwner) : TOleControl(AOwner)
  {};
  virtual  __fastcall TSigCtlXHTML(HWND        Parent) : TOleControl(Parent)
  {};

  // OCX methods
  //
  Flsigctllib_tlb::CaptureResult __fastcall Capture(BSTR Who/*[in]*/, BSTR Why/*[in]*/, 
                                                    VARIANT What/*[in,opt]*/= TNoParam(), 
                                                    VARIANT Key/*[in,opt]*/= TNoParam());
  void            __fastcall AboutBox(void);
  VARIANT_BOOL    __fastcall SetProperty(BSTR Name/*[in]*/, VARIANT Value/*[in]*/);
  VARIANT         __fastcall GetProperty(BSTR Name/*[in]*/);
  Flsigctllib_tlb::SignedData __fastcall CheckHostDocument(void);
  Flsigctllib_tlb::SignedData __fastcall CheckHostDocument2(void);
  void            __fastcall InsertMarkup(BSTR Id/*[in]*/, BSTR Text/*[in]*/);

  // OCX properties
  //
  __property _di_IDispatch Signature={ read=GetIDispatchProp, write=SetIDispatchProp, index=1 };
  __property VARIANT AppData[VARIANT Key]={ read=get_AppData, write=set_AppData };
  __property _di_IDispatch Printer={ read=GetIDispatchProp, index=100 };
  __property System::OleVariant Licence={ read=GetOleVariantProp, write=SetOleVariantProp, index=101 };
  __property System::WideString Properties={ write=SetWideStringProp, index=102 };
  __property ISigCtlXHTML4Disp ControlInterface={ read=GetDefaultInterface };

  // Published properties
  //
__published:

  // Standard/Extended properties
  //
  __property ParentColor;
  __property ParentFont;
  __property Align;
  __property DragCursor;
  __property DragMode;
  __property ParentShowHint;
  __property PopupMenu;
  __property ShowHint;
  __property TabOrder;
  __property Visible;
  __property OnDragDrop;
  __property OnDragOver;
  __property OnEndDrag;
  __property OnEnter;
  __property OnExit;
  __property OnStartDrag;
  __property OnMouseUp;
  __property OnMouseMove;
  __property OnMouseDown;
  __property OnKeyUp;
  __property OnKeyPress;
  __property OnKeyDown;
  __property OnDblClick;
  __property OnClick;

  // OCX properties
  //
  __property Graphics::TColor BackColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=-501 };
  __property int BackStyle={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=-502 };
  __property Graphics::TColor BorderColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=-503 };
  __property int BorderStyle={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=-504 };
  __property int BorderWidth={ read=GetIntegerProp, write=SetIntegerProp, stored=false, index=-505 };
  __property Graphics::TFont * Font={ read=GetTFontProp, write=_SetTFontProp, stored=false, index=-512 };
  __property Graphics::TColor ForeColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=-513 };
  __property bool Enabled={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=-514 };
  __property bool TabStop={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=-516 };
  __property System::WideString Caption={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=-518 };
  __property bool BorderVisible={ read=GetWordBoolProp, write=SetWordBoolProp, stored=false, index=-519 };
  __property short CtlPadding={ read=GetSmallintProp, write=SetSmallintProp, stored=false, index=2 };
  __property Activex::TOleEnum DisplayMode={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=3 };
  __property short Zoom={ read=GetSmallintProp, write=SetSmallintProp, stored=false, index=4 };
  __property short Rotation={ read=GetSmallintProp, write=SetSmallintProp, stored=false, index=5 };
  __property Graphics::TColor InkColor={ read=GetTColorProp, write=SetTColorProp, stored=false, index=6 };
  __property float InkWidth={ read=GetSingleProp, write=SetSingleProp, stored=false, index=7 };
  __property Activex::TOleEnum ShowWho={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=8 };
  __property Activex::TOleEnum ShowWhen={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=9 };
  __property Activex::TOleEnum ShowWhy={ read=GetTOleEnumProp, write=SetTOleEnumProp, stored=false, index=12 };
  __property System::WideString WhenFormat={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=10 };
  __property System::WideString InputWho={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=13 };
  __property System::WideString InputWhy={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=14 };
  __property System::WideString InputData={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=15 };
  __property System::WideString InputSignature={ read=GetWideStringProp, write=SetWideStringProp, stored=false, index=16 };

  // OCX Events
  //
  __property TSigCtlXHTMLPreCapture OnPreCapture={ read=FOnPreCapture, write=FOnPreCapture };
  __property TSigCtlXHTMLPostCapture OnPostCapture={ read=FOnPostCapture, write=FOnPostCapture };
  __property TNotifyEvent OnRemove={ read=FOnRemove, write=FOnRemove };
};
typedef TSigCtlXHTML  TSigCtlXHTMLProxy;


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TImgCtlXHTML
// Help String      : ImgCtlXHTML Class
// Default Interface: IImgCtlXHTML3
// Def. Intf. Object: IImgCtlXHTML3Disp
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//

// *********************************************************************//
// Definition of closures to allow VCL handlers to catch OCX events.      
// *********************************************************************//
//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
// Proxy class to host ImgCtlXHTML Class in CBuilder IDE/Applications.
//-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
class PACKAGE TImgCtlXHTML : public TOleControl
{
  OVERLOADED_PROP_METHODS;
  static TNoParam  OptParam;
  static GUID      DEF_CTL_INTF;

  // Instance of Closures to expose OCX Events as VCL ones
  //

  // Default Interace of OCX
  //
  IImgCtlXHTML3Disp m_OCXIntf;

  // VCL Property Getters/Setters which delegate to OCX
  //
  VARIANT         __fastcall get_Licence(void);
  void            __fastcall set_Licence(VARIANT pVal/*[in]*/);

  // Static variables used by all instances of OCX proxy
  //
  static TControlData2 CControlData;
  static GUID          CTL_DEF_INTF;

  // Method providing access to interface as __property 
  //
  IImgCtlXHTML3Disp __fastcall GetDefaultInterface();
  IImgCtlXHTML3Disp __fastcall GetControlInterface()
  { return GetDefaultInterface(); }

protected:
  void     __fastcall CreateControl  ();
  void     __fastcall InitControlData();

public:
  virtual  __fastcall TImgCtlXHTML(TComponent* AOwner) : TOleControl(AOwner)
  {};
  virtual  __fastcall TImgCtlXHTML(HWND        Parent) : TOleControl(Parent)
  {};

  // OCX methods
  //

  // OCX properties
  //
  __property System::OleVariant Licence={ read=GetOleVariantProp, write=SetOleVariantProp, index=4 };
  __property System::WideString Properties={ write=SetWideStringProp, index=5 };
  __property IImgCtlXHTML3Disp ControlInterface={ read=GetDefaultInterface };

  // Published properties
  //
__published:

  // Standard/Extended properties
  //
  __property TabStop;
  __property Align;
  __property DragCursor;
  __property DragMode;
  __property ParentShowHint;
  __property PopupMenu;
  __property ShowHint;
  __property TabOrder;
  __property Visible;
  __property OnDragDrop;
  __property OnDragOver;
  __property OnEndDrag;
  __property OnEnter;
  __property OnExit;
  __property OnStartDrag;

  // OCX properties
  //

  // OCX Events
  //
};
typedef TImgCtlXHTML  TImgCtlXHTMLProxy;


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TOnLoadHandler
// Help String      : OnLoadHandler Class
// Default Interface: IOnLoadHandler
// Def. Intf. Object: IOnLoadHandlerPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TOnLoadHandler : public Oleserver::TOleServer
{
  IOnLoadHandlerPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TOnLoadHandler(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  IOnLoadHandlerPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(IOnLoadHandlerPtr intf);


  void            __fastcall OnLoad(void);
};


// *********************************************************************//
// COM Component Proxy Class Declaration
// Component Name   : TCustomSetup
// Help String      : CustomSetup Class
// Default Interface: ICustomSetup
// Def. Intf. Object: ICustomSetupPtr
// Def. Intf. DISP? : No
// Event   Interface: 
// TypeFlags        : (2) CanCreate
// *********************************************************************//
class PACKAGE TCustomSetup : public Oleserver::TOleServer
{
  ICustomSetupPtr m_DefaultIntf;
  _di_IUnknown __fastcall GetDunk();
public:
  __fastcall TCustomSetup(TComponent* owner) : Oleserver::TOleServer(owner)
  {}

  ICustomSetupPtr& GetDefaultInterface();
  void __fastcall InitServerData();
  void __fastcall Connect();
  void __fastcall Disconnect();
  void __fastcall BeforeDestruction();
  void __fastcall ConnectTo(ICustomSetupPtr intf);


  short           __fastcall Initialize(BSTR P1/*[in]*/, BSTR P2/*[in]*/);
};

};     // namespace Flsigctllib_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Flsigctllib_tlb;
#endif

#pragma option pop

#endif // FLSIGCTLLib_OCXH
