object frmAlphaDoc8: TfrmAlphaDoc8
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  ClientHeight = 877
  ClientWidth = 1240
  Color = clWhite
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = #44404#47548#52404
  Font.Style = []
  OldCreateOrder = False
  Position = poDesigned
  OnClose = FormClose
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 12
  object panMain: TPanel
    Left = 0
    Top = 0
    Width = 1240
    Height = 877
    BevelOuter = bvNone
    DoubleBuffered = True
    Font.Charset = HANGEUL_CHARSET
    Font.Color = clBlack
    Font.Height = -24
    Font.Name = #44404#47548#52404
    Font.Style = []
    ParentDoubleBuffered = False
    ParentFont = False
    TabOrder = 0
    object IMGSCREEN2: TImage
      Left = 0
      Top = 0
      Width = 1240
      Height = 877
      Stretch = True
    end
    object pbRect2: TPaintBox
      Tag = 2
      Left = 0
      Top = 0
      Width = 1240
      Height = 877
      Align = alClient
      Color = clBlack
      ParentColor = False
      ExplicitLeft = 49
      ExplicitTop = 32
      ExplicitWidth = 50
      ExplicitHeight = 50
    end
  end
end
